name: fuse
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.05.30=h06a4308_0
  - certifi=2023.5.7=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=39.0.1=py39h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.6=py39h417a72b_1
  - mkl_random=1.2.2=py39h417a72b_1
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.24.3=py39hf6e8229_1
  - numpy-base=1.24.3=py39h060ed82_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - pillow=9.4.0=py39h6a678d5_0
  - pip=23.0.1=py39h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.16=h7a1cb2a_2
  - pytorch=1.12.1=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.29.0=py39h06a4308_0
  - setuptools=67.8.0=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py39_cu113
  - torchvision=0.13.1=py39_cu113
  - typing_extensions=4.5.0=py39h06a4308_0
  - urllib3=1.26.16=py39h06a4308_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - absl-py==1.4.0
    - addict==2.4.0
    - appdirs==1.4.4
    - apptools==5.2.0
    - asttokens==2.2.1
    - attrs==23.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - cachetools==5.3.1
    - click==8.1.3
    - comm==0.1.3
    - configargparse==1.5.3
    - configobj==5.0.8
    - contourpy==1.0.7
    - cycler==0.11.0
    - cython==0.29.35
    - dash==2.10.2
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - debugpy==1.6.7
    - decorator==5.1.1
    - deepspeed==0.9.3
    - docker-pycreds==0.4.0
    - easydict==1.10
    - envisage==7.0.3
    - executing==1.2.0
    - fastjsonschema==2.17.1
    - filelock==3.12.0
    - flask==2.2.5
    - fonttools==4.39.4
    - gdown==4.7.1
    - gitdb==4.0.10
    - gitpython==3.1.31
    - google-auth==2.19.1
    - google-auth-oauthlib==1.0.0
    - grpcio==1.54.2
    - h5py==3.8.0
    - hjson==3.1.0
    - importlib-metadata==6.6.0
    - importlib-resources==5.12.0
    - ipykernel==6.23.1
    - ipython==8.14.0
    - ipywidgets==8.0.6
    - itsdangerous==2.1.2
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.3
    - jupyter-client==8.2.0
    - jupyter-core==5.3.0
    - jupyterlab-widgets==3.0.7
    - kiwisolver==1.4.4
    - markdown==3.4.3
    - markupsafe==2.1.3
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mayavi==4.8.1
    - multimethod==1.9.1
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - ninja==1.11.1
    - oauthlib==3.2.2
    - open3d==0.17.0
    - opencv-python==4.7.0.72
    - packaging==23.1
    - pandas==2.0.2
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==3.5.1
    - plotly==5.15.0
    - pooch==1.7.0
    - prompt-toolkit==3.0.38
    - protobuf==4.23.2
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py-cpuinfo==9.0.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pydantic==1.10.9
    - pyface==8.0.0
    - pygments==2.15.1
    - pyparsing==3.0.9
    - pyquaternion==0.9.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pyvista==0.39.1
    - pyyaml==6.0
    - pyzmq==25.1.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - scooby==0.7.2
    - seaborn==0.12.2
    - sentry-sdk==1.25.1
    - setproctitle==1.3.2
    - six==1.16.0
    - smmap==5.0.0
    - soupsieve==2.4.1
    - stack-data==0.6.2
    - tenacity==8.2.2
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.0
    - termcolor==2.3.0
    - threadpoolctl==3.1.0
    - tornado==6.3.2
    - tqdm==4.65.0
    - traitlets==5.9.0
    - traits==6.4.1
    - traitsui==8.0.0
    - tzdata==2023.3
    - vtk==9.2.6
    - wandb==0.15.4
    - wcwidth==0.2.6
    - werkzeug==2.2.3
    - widgetsnbextension==4.0.7
    - zipp==3.15.0
prefix: /home/tasarma/miniconda3/envs/fuse
