name: fusion
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - cudatoolkit=11.3.1=ha36c431_9
  - ffmpeg=4.3=hf484d3e_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - importlib-metadata=4.11.3=py37h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libllvm11=11.1.0=h9e868ea_6
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.44.2=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - llvmlite=0.39.1=py37he621ea3_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numba=0.56.4=py37h417a72b_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - pillow=9.4.0=py37h6a678d5_0
  - pip=22.3.1=py37h06a4308_0
  - python=3.7.16=h7a1cb2a_0
  - pytorch=1.10.1=py3.7_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.1=h5eee18b_0
  - tbb=2021.7.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchvision=0.11.2=py37_cu113
  - typing_extensions=4.4.0=py37h06a4308_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zipp=3.11.0=py37h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.4.0
    - addict==2.4.0
    - appdirs==1.4.4
    - apptools==5.2.0
    - attrs==22.2.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.2
    - cached-property==1.5.2
    - cachetools==5.3.0
    - charset-normalizer==3.1.0
    - click==8.1.3
    - configargparse==1.5.3
    - configobj==5.0.8
    - cycler==0.11.0
    - cython==0.29.28
    - dash==2.9.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - decorator==5.1.1
    - deepspeed==0.8.2
    - docker-pycreds==0.4.0
    - easydict==1.9
    - envisage==7.0.1
    - fastjsonschema==2.16.3
    - filelock==3.10.0
    - flask==2.2.3
    - fonttools==4.38.0
    - gdown==4.6.4
    - gitdb==4.0.10
    - gitpython==3.1.31
    - google-auth==2.16.2
    - google-auth-oauthlib==0.4.6
    - grpcio==1.51.3
    - h5py==3.6.0
    - hjson==3.1.0
    - idna==3.4
    - imageio==2.26.1
    - importlib-resources==5.12.0
    - ipython==7.34.0
    - ipywidgets==8.0.5
    - itsdangerous==2.1.2
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.3
    - jupyter-core==4.12.0
    - jupyterlab-widgets==3.0.6
    - kiwisolver==1.4.4
    - markdown==3.4.1
    - markupsafe==2.1.2
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.6
    - mayavi==4.8.1
    - multimethod==1.7
    - nbformat==5.7.0
    - ninja==1.10.2.3
    - numpy==1.21.6
    - oauthlib==3.2.2
    - open3d==0.17.0
    - opencv-python==4.7.0.72
    - packaging==23.0
    - pandas==1.3.5
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.1.1
    - plotly==5.13.1
    - pointnet2==0.0.0
    - pooch==1.7.0
    - prompt-toolkit==3.0.38
    - protobuf==3.19.4
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - py-cpuinfo==9.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.10.6
    - pyface==7.4.4
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pyqt5==5.15.9
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.1
    - pyquaternion==0.9.9
    - pyrsistent==0.19.3
    - pyside6==6.4.3
    - pyside6-addons==6.4.3
    - pyside6-essentials==6.4.3
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - pytz==2022.7.1
    - pyvista==0.38.5
    - pyyaml==6.0
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - scooby==0.7.1
    - seaborn==0.12.2
    - sentry-sdk==1.17.0
    - setproctitle==1.3.2
    - setuptools==67.6.1
    - shiboken6==6.4.3
    - smmap==5.0.0
    - soupsieve==2.4
    - tenacity==8.2.2
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-logger==0.1.0
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - thop==0.1.1-2209072238
    - threadpoolctl==3.1.0
    - tqdm==4.65.0
    - traitlets==5.9.0
    - traits==6.4.1
    - traitsui==7.4.3
    - ultralytics==8.0.55
    - urllib3==1.26.15
    - vtk==9.2.6
    - wandb==0.14.0
    - wcwidth==0.2.6
    - werkzeug==2.2.3
    - widgetsnbextension==4.0.6
prefix: /home/tasarma/miniconda3/envs/fusion
